services:
  frontend:
    build:
      context: ./frontend
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_INTERNAL_PORT}"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:${BACKEND_PORT}
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - database
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${BACKEND_PORT}
      - MONGODB_URI=${MONGODB_URI}
      - STUN_SERVERS=${STUN_SERVERS}
      - TURN_SERVER_URL=${TURN_SERVER_URL}
      - TURN_SERVER_USERNAME=${TURN_SERVER_USERNAME}
      - TURN_SERVER_CREDENTIAL=${TURN_SERVER_CREDENTIAL}
      - DEFAULT_DHT_SERVICES=${DEFAULT_DHT_SERVICES}
    env_file:
      - .env
    command: >
      sh -c "npm start & sleep 10 && node src/scripts/init-dht.js && node src/scripts/init-ice.js && wait"


  database:
    build:
      context: ./database
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env

  nginx:
    build:
      context: ./nginx
    ports:
      - "${EXTERNAL_PORT}:${NGINX_INTERNAL_PORT}"
    environment:
      - DHT_DOMAIN=${DHT_DOMAIN}
      - DHT_INTERNAL_PORT=${DHT_INTERNAL_PORT}
      - STUN_DOMAIN=${STUN_DOMAIN}
      - STUN_INTERNAL_PORT=${STUN_INTERNAL_PORT}
      - NGINX_INTERNAL_PORT=${NGINX_INTERNAL_PORT}
    depends_on:
      - dht
      - stunturn
    restart: unless-stopped

  dht:
    build:
      context: ./dht
      args:
        - PORT=${DHT_INTERNAL_PORT}
    environment:
      - PORT=${DHT_INTERNAL_PORT}
      - HOST=0.0.0.0
    volumes:
      - ./dht:/app
      - /app/node_modules
    restart: unless-stopped
    env_file:
      - .env

  stunturn:
    build:
      context: ./stunturn
    network_mode: host
    volumes:
      - ./stunturn/turnserver.conf:/etc/coturn/turnserver.conf
    restart: unless-stopped
    command: 
      - -c /etc/coturn/turnserver.conf

volumes:
  mongo-data: