services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "${EXTERNAL_PORT}:${EXTERNAL_PORT}"
    environment:
      - DHT_DOMAIN=${DHT_DOMAIN}
      - DHT_INTERNAL_PORT=${DHT_INTERNAL_PORT}
      - STUN_DOMAIN=${STUN_DOMAIN}
      - STUN_INTERNAL_PORT=${STUN_INTERNAL_PORT}
      - EXTERNAL_PORT=${EXTERNAL_PORT}
    depends_on:
      - dht
      - stunturn
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - p2pnet

  dht:
    build:
      context: ./dht
      args:
        - PORT=${DHT_INTERNAL_PORT}
    environment:
      - PORT=${DHT_INTERNAL_PORT}
      - HOST=0.0.0.0
    volumes:
      - ./dht:/app
      - /app/node_modules
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - p2pnet

  stunturn:
    build:
      context: ./stunturn
      args:
        - STUN_INTERNAL_PORT=${STUN_INTERNAL_PORT}
        - TURN_INTERNAL_PORT=${TURN_INTERNAL_PORT}
        - MIN_TURN_PORT=${MIN_TURN_PORT}
        - MAX_TURN_PORT=${MAX_TURN_PORT}
    network_mode: host
    volumes:
      - ./stunturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
    restart: unless-stopped
    env_file:
      - .env

networks:
  p2pnet:
    driver: bridge